/**
 * Référentiel géographique France : département + région à partir d'un code postal.
 * Sert à enrichir les pages SEO (contexte unique par zone → évite le contenu dupliqué)
 * et pourra resservir ailleurs (Baromètre, filtres, etc.). Données stables, pures.
 */
export type DeptInfo = { num: string; nom: string; region: string };

/** Métropole : code département (2 chiffres) → { nom, région }. Corse et Outre-mer gérés à part. */
const DEPT: Record<string, { nom: string; region: string }> = {
  "01": { nom: "Ain", region: "Auvergne-Rhône-Alpes" },
  "02": { nom: "Aisne", region: "Hauts-de-France" },
  "03": { nom: "Allier", region: "Auvergne-Rhône-Alpes" },
  "04": { nom: "Alpes-de-Haute-Provence", region: "Provence-Alpes-Côte d'Azur" },
  "05": { nom: "Hautes-Alpes", region: "Provence-Alpes-Côte d'Azur" },
  "06": { nom: "Alpes-Maritimes", region: "Provence-Alpes-Côte d'Azur" },
  "07": { nom: "Ardèche", region: "Auvergne-Rhône-Alpes" },
  "08": { nom: "Ardennes", region: "Grand Est" },
  "09": { nom: "Ariège", region: "Occitanie" },
  "10": { nom: "Aube", region: "Grand Est" },
  "11": { nom: "Aude", region: "Occitanie" },
  "12": { nom: "Aveyron", region: "Occitanie" },
  "13": { nom: "Bouches-du-Rhône", region: "Provence-Alpes-Côte d'Azur" },
  "14": { nom: "Calvados", region: "Normandie" },
  "15": { nom: "Cantal", region: "Auvergne-Rhône-Alpes" },
  "16": { nom: "Charente", region: "Nouvelle-Aquitaine" },
  "17": { nom: "Charente-Maritime", region: "Nouvelle-Aquitaine" },
  "18": { nom: "Cher", region: "Centre-Val de Loire" },
  "19": { nom: "Corrèze", region: "Nouvelle-Aquitaine" },
  "21": { nom: "Côte-d'Or", region: "Bourgogne-Franche-Comté" },
  "22": { nom: "Côtes-d'Armor", region: "Bretagne" },
  "23": { nom: "Creuse", region: "Nouvelle-Aquitaine" },
  "24": { nom: "Dordogne", region: "Nouvelle-Aquitaine" },
  "25": { nom: "Doubs", region: "Bourgogne-Franche-Comté" },
  "26": { nom: "Drôme", region: "Auvergne-Rhône-Alpes" },
  "27": { nom: "Eure", region: "Normandie" },
  "28": { nom: "Eure-et-Loir", region: "Centre-Val de Loire" },
  "29": { nom: "Finistère", region: "Bretagne" },
  "30": { nom: "Gard", region: "Occitanie" },
  "31": { nom: "Haute-Garonne", region: "Occitanie" },
  "32": { nom: "Gers", region: "Occitanie" },
  "33": { nom: "Gironde", region: "Nouvelle-Aquitaine" },
  "34": { nom: "Hérault", region: "Occitanie" },
  "35": { nom: "Ille-et-Vilaine", region: "Bretagne" },
  "36": { nom: "Indre", region: "Centre-Val de Loire" },
  "37": { nom: "Indre-et-Loire", region: "Centre-Val de Loire" },
  "38": { nom: "Isère", region: "Auvergne-Rhône-Alpes" },
  "39": { nom: "Jura", region: "Bourgogne-Franche-Comté" },
  "40": { nom: "Landes", region: "Nouvelle-Aquitaine" },
  "41": { nom: "Loir-et-Cher", region: "Centre-Val de Loire" },
  "42": { nom: "Loire", region: "Auvergne-Rhône-Alpes" },
  "43": { nom: "Haute-Loire", region: "Auvergne-Rhône-Alpes" },
  "44": { nom: "Loire-Atlantique", region: "Pays de la Loire" },
  "45": { nom: "Loiret", region: "Centre-Val de Loire" },
  "46": { nom: "Lot", region: "Occitanie" },
  "47": { nom: "Lot-et-Garonne", region: "Nouvelle-Aquitaine" },
  "48": { nom: "Lozère", region: "Occitanie" },
  "49": { nom: "Maine-et-Loire", region: "Pays de la Loire" },
  "50": { nom: "Manche", region: "Normandie" },
  "51": { nom: "Marne", region: "Grand Est" },
  "52": { nom: "Haute-Marne", region: "Grand Est" },
  "53": { nom: "Mayenne", region: "Pays de la Loire" },
  "54": { nom: "Meurthe-et-Moselle", region: "Grand Est" },
  "55": { nom: "Meuse", region: "Grand Est" },
  "56": { nom: "Morbihan", region: "Bretagne" },
  "57": { nom: "Moselle", region: "Grand Est" },
  "58": { nom: "Nièvre", region: "Bourgogne-Franche-Comté" },
  "59": { nom: "Nord", region: "Hauts-de-France" },
  "60": { nom: "Oise", region: "Hauts-de-France" },
  "61": { nom: "Orne", region: "Normandie" },
  "62": { nom: "Pas-de-Calais", region: "Hauts-de-France" },
  "63": { nom: "Puy-de-Dôme", region: "Auvergne-Rhône-Alpes" },
  "64": { nom: "Pyrénées-Atlantiques", region: "Nouvelle-Aquitaine" },
  "65": { nom: "Hautes-Pyrénées", region: "Occitanie" },
  "66": { nom: "Pyrénées-Orientales", region: "Occitanie" },
  "67": { nom: "Bas-Rhin", region: "Grand Est" },
  "68": { nom: "Haut-Rhin", region: "Grand Est" },
  "69": { nom: "Rhône", region: "Auvergne-Rhône-Alpes" },
  "70": { nom: "Haute-Saône", region: "Bourgogne-Franche-Comté" },
  "71": { nom: "Saône-et-Loire", region: "Bourgogne-Franche-Comté" },
  "72": { nom: "Sarthe", region: "Pays de la Loire" },
  "73": { nom: "Savoie", region: "Auvergne-Rhône-Alpes" },
  "74": { nom: "Haute-Savoie", region: "Auvergne-Rhône-Alpes" },
  "75": { nom: "Paris", region: "Île-de-France" },
  "76": { nom: "Seine-Maritime", region: "Normandie" },
  "77": { nom: "Seine-et-Marne", region: "Île-de-France" },
  "78": { nom: "Yvelines", region: "Île-de-France" },
  "79": { nom: "Deux-Sèvres", region: "Nouvelle-Aquitaine" },
  "80": { nom: "Somme", region: "Hauts-de-France" },
  "81": { nom: "Tarn", region: "Occitanie" },
  "82": { nom: "Tarn-et-Garonne", region: "Occitanie" },
  "83": { nom: "Var", region: "Provence-Alpes-Côte d'Azur" },
  "84": { nom: "Vaucluse", region: "Provence-Alpes-Côte d'Azur" },
  "85": { nom: "Vendée", region: "Pays de la Loire" },
  "86": { nom: "Vienne", region: "Nouvelle-Aquitaine" },
  "87": { nom: "Haute-Vienne", region: "Nouvelle-Aquitaine" },
  "88": { nom: "Vosges", region: "Grand Est" },
  "89": { nom: "Yonne", region: "Bourgogne-Franche-Comté" },
  "90": { nom: "Territoire de Belfort", region: "Bourgogne-Franche-Comté" },
  "91": { nom: "Essonne", region: "Île-de-France" },
  "92": { nom: "Hauts-de-Seine", region: "Île-de-France" },
  "93": { nom: "Seine-Saint-Denis", region: "Île-de-France" },
  "94": { nom: "Val-de-Marne", region: "Île-de-France" },
  "95": { nom: "Val-d'Oise", region: "Île-de-France" },
};

const DOM: Record<string, string> = {
  "971": "Guadeloupe",
  "972": "Martinique",
  "973": "Guyane",
  "974": "La Réunion",
  "976": "Mayotte",
};

/** Département + région depuis un code postal. Défaut prudent si inconnu. */
export function deptInfo(cp: string): DeptInfo {
  const d = (cp || "").replace(/\D/g, "");
  const dom = DOM[d.slice(0, 3)];
  if (dom) return { num: d.slice(0, 3), nom: dom, region: `${dom} (Outre-mer)` };
  if (d.slice(0, 2) === "20") return { num: "20", nom: "Corse", region: "Corse" };
  const hit = DEPT[d.slice(0, 2)];
  return hit ? { num: d.slice(0, 2), nom: hit.nom, region: hit.region } : { num: d.slice(0, 2), nom: "", region: "" };
}
